
# replace default parameters by your config
# -r = remove-adapter-fwd (str)
# -c = remove-adapter-rev (str)
# -x = min x kmer coverage in a read (int) 
# -k = size of kmer (int)
# -m = minimum overlap required between two reads to merge (int)
# -t = number of thread (int)

REF:= /tmp/SA564.fa
REF_GFF:= /tmp/SA564.gff
SGA_PREPROC_FLAGS:= -r AGATCGGAAGAGCACACGTCTGAACTCCAGTC -c AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTG
SGA_FILTER_FLAGS:= -x15 -k61
SGA_FMMERGE_FLAGS:= -m61
SGA_KMERCOUNT_FLAGS:= -k61
SGA_THREAD:= -t4
SGA_OVERLAP_FLAGS:= -m61
KMER_FILTER_THRESHOLD:= 10
